### ISSUE TITLE
Ненужный метод

### ISSUE THREAD

**Issue by ShkiTTer** [kralonur/NotForgot#8]
https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/ui/task_create/TaskCreateFragment.kt#L206-L208

Если не нужен слушатель клика для кнопки диалога можно просто передать null

**Comment by ShkiTTer** [comment]
https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/ui/task_create/TaskCreateFragment.kt#L285-L299

А вот здесь наоборот лучше было бы передать обработчик клика при создании диалога

**Comment by kralonur** [comment]
> А вот здесь наоборот лучше было бы передать обработчик клика при создании диалога

Unfortunatelly no, because when I set PositiveButton when creating dialog, dialog closes itself after clicking button. That's why I can't set click listener when creating dialog. And that's why I set it null first then created clickListener. So I want to close dialog when creatingCategory successful not when I clicked the button.

**Comment by ShkiTTer** [comment]
https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/repository/ItemsRepository.kt#L200-L201

https://github.com/kralonur/NotForgot/blob/e8d35e67573b0a14088888e013aa08016a279d15/app/src/main/java/com/example/notforgot/repository/ItemsRepository.kt#L182-L183

Пустые методы, которые также не нужны

**Comment by kralonur** [comment]
Issue fixed.
